# Generated by Django 3.0.7 on 2020-06-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0003_auto_20200624_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='merchants',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
