# Generated by Django 3.0.7 on 2020-06-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0006_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='merchants',
            options={},
        ),
    ]
