# Generated by Django 3.0.7 on 2020-06-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0007_auto_20200625_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='pincode',
            field=models.IntegerField(blank=True, db_column='pin', null=True),
        ),
        migrations.AddField(
            model_name='merchants',
            name='pincode',
            field=models.IntegerField(blank=True, db_column='pin', null=True),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='account_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
