# Generated by Django 3.0.7 on 2020-06-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0008_auto_20200625_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
