# Generated by Django 3.0.7 on 2020-06-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0010_auto_20200625_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sus2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sus2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sus5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sus5',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SignupPhonemodel',
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='merchants',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
