# Generated by Django 3.0.7 on 2020-06-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0011_auto_20200626_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchants',
            options={},
        ),
    ]
