# Generated by Django 3.0.7 on 2020-06-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0012_auto_20200626_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchants',
            name='pincode',
        ),
        migrations.AddField(
            model_name='merchants',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='merchants',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='merchants',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
