# Generated by Django 3.0.7 on 2020-06-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0014_auto_20200629_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantsInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Merchants_Inventory',
                'managed': False,
            },
        ),
    ]
