# Generated by Django 3.0.7 on 2020-06-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0015_merchantsinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantsinventory',
            options={},
        ),
    ]
