# Generated by Django 3.0.7 on 2020-06-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0016_auto_20200630_0710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Sus',
        ),
        migrations.DeleteModel(
            name='Sus2',
        ),
        migrations.DeleteModel(
            name='Sus5',
        ),
        migrations.AlterModelOptions(
            name='merchantsinventory',
            options={'managed': False},
        ),
    ]
