# Generated by Django 3.0.7 on 2020-06-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0019_auto_20200630_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
    ]
