# Generated by Django 3.0.7 on 2020-06-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0022_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='SignupPhonemodel',
        ),
    ]
