# Generated by Django 3.0.7 on 2020-06-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0024_djangomigrations_signupphonemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
