# Generated by Django 3.0.7 on 2020-06-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0026_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='merchants',
            options={},
        ),
        migrations.AlterModelOptions(
            name='merchantsinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='signupphonemodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
