# Generated by Django 3.0.7 on 2020-06-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0028_auto_20200630_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
    ]
