# Generated by Django 3.0.7 on 2020-06-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0029_auto_20200630_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cid',
            field=models.ForeignKey(db_column='cid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='SignUp.Customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
