# Generated by Django 3.0.7 on 2020-06-30 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0030_auto_20200630_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='inv_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
