# Generated by Django 3.0.7 on 2020-06-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0033_auto_20200630_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': False},
        ),
    ]
