# Generated by Django 3.0.7 on 2020-06-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0034_auto_20200630_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
    ]
