# Generated by Django 3.0.7 on 2020-06-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0036_auto_20200630_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
    ]
