# Generated by Django 3.0.7 on 2020-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0037_auto_20200630_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchants',
            options={},
        ),
    ]
