# Generated by Django 3.0.7 on 2020-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0038_auto_20200701_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='subscribers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
