# Generated by Django 3.0.7 on 2020-07-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0042_auto_20200701_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchants',
            options={},
        ),
    ]
