# Generated by Django 3.0.7 on 2020-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0044_remove_merchants_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='subscribers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
