# Generated by Django 3.0.7 on 2020-07-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0045_merchants_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='merchants',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
