# Generated by Django 3.0.7 on 2020-07-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0046_auto_20200701_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
    ]
