# Generated by Django 3.0.7 on 2020-07-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0048_auto_20200701_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='merchants',
            options={},
        ),
    ]
